CREATE PROCEDURE OR REPLACE LABPRACTICE
AS
REGIONS_ID1 REGIONS.REGION_ID%TYPE;
REGIONS_ID2 REGIONS.REGION_ID%TYPE;
REGIONS_ID3 REGIONS.REGION_ID%TYPE;
REGION_NAME1 REGIONS.REGION_NAME%TYPE;
REGION_NAME2 REGIONS.REGION_NAME%TYPE;
REGION_NAME3 REGIONS.REGION_NAME%TYPE;
BEGIN
REGIONS_ID1 := &REGIONS_ID1;
REGIONS_ID2 := &REGIONS_ID2;
REGIONS_ID3 := &REGIONS_ID3;
REGION_NAME1 := &REGION_NAME1;
REGION_NAME2 := &REGION_NAME2;
REGION_NAME3 := &REGION_NAME3;

INSERT INTO REGIONS_COPY(REGION_ID, REGION_NAME) VALUES (REGIONS_ID1, REGION_NAME1);
INSERT INTO REGIONS_COPY(REGION_ID, REGION_NAME) VALUES (REGIONS_ID2, REGION_NAME2);
INSERT INTO REGIONS_COPY(REGION_ID, REGION_NAME) VALUES (REGIONS_ID3, REGION_NAME3);
END;
